fail_fast: False

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: no-commit-to-branch

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff-check
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format

  - repo: https://github.com/alessio-locatelli/ruff-extra-rules
    rev: v0.4.6
    hooks:
      - id: ruff-extra-rules

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.16
    hooks:
      - id: vulture

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.18
    hooks:
      - id: uv-lock
        args: ["--check"]

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
        args: []

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  - repo: https://github.com/lycheeverse/lychee.git
    rev: lychee-v0.24.2
    hooks:
      - id: lychee

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v2.3.1"
    hooks:
      - id: mypy
        args: []
        additional_dependencies:
          [
            pendulum,
            pydantic,
            python-dateutil,
            arrow,
            udatetime,
            pytest,
            pytest-benchmark,
            faker,
            pandas,
            pandas-stubs,
            types-python-dateutil,
          ]
