target-version = "py314"

extend-exclude = [
  ".cache",
  ".pytest_cache",
  ".vscode",
  "data",
  "docs",
  "resources",
  "pdoc",
]
force-exclude = true

[lint]
ignore = [
  # unnecessary-collection-call
  "C408",
  "D",
  # assert
  "S101",
  # commented-out-code
  "ERA001",
  # missing-copyright-notice
  "CPY001",
]
select = ["ALL"]
